###################################################################################################
# Upload an image from a local file named 'filename'
- name: Deploy on OpenStack
  hosts: 10.81.1.141
  gather_facts: false
  tasks:
  - name:
    os_image:
      auth:
        auth_url: http://10.81.1.141:5000/v3/
        username: asad
        password: pakistan
        project_name: gocha1
        user_domain_name: default
        project_domain_name: default
      name: cirros
      container_format: bare
      disk_format: qcow2
      state: present
      filename: root/scripts/cirros-0.3.0-x86_64-disk.img
      kernel: cirros-vmlinuz
      ramdisk: cirros-initrd
      properties:
        cpu_arch: x86_64
        distro: ubuntu 

