- name: Deploy on OpenStack
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create the test network
    os_network:
      state: present
      auth:
        auth_url: http://10.81.1.11:5000/v3/
        username: asad
        password: asad
        project_name: gocha1
        user_domain_name: default
        project_domain_name: default
      name: testnet25
      external: False
      shared: False
      provider_network_type: vxlan
      provider_physical_network: ~

