###################################################################################################
# It will create a flavor on openstack.

- name: Deploy on OpenStack
  hosts: 10.81.1.142
  gather_facts: false
  tasks:
  - name: Create tiny flavor with some specs
    os_nova_flavor:
      state: present
      auth:
         auth_url: http://10.81.1.141:5000/v3
         username: asad
         password: pakistan
         project_name: gocha1
         user_domain_name: default
         project_domain_name: default
      name: tiny
      ram: 512
      vcpus: 1
      disk: 2
      ephemeral: 2
      rxtx_factor: 1
      endpoint_type: admin
