###################################################################################################
# It will create a router on openstack

- name: Deploy on OpenStack
  hosts: 10.81.1.142
  gather_facts: false
  tasks:
  - name: Create a demo router
    os_router:
      state: present
      auth:
         auth_url: http://10.81.1.141:5000/v3
         username: asad
         password: pakistan
         project_name: gocha1
         user_domain_name: default
         project_domain_name: default
      name: demorouter
      project: gocha1 
