###################################################################################################
# It will create a security group in openstack under network section.

- name: Deploy on OpenStack
  hosts: 10.81.1.142
  gather_facts: false
  tasks:
  - name: Create a security group
    os_security_group:
      state: present
      auth:
        auth_url: http://10.81.1.141:5000/v3
        username: asad
        password: pakistan
        project_name: gocha1
        user_domain_name: default
        project_domain_name: default
      name: apple
      description: security group for apple servers
